### ISSUE TITLE
No icon for desktop file

### ISSUE THREAD

**Issue by papoteur-mga** [redtide/picom-conf#37]
desktop file for including in menus refers to `Icon=picom`.
However nothing provides the icon.
`picom` has still `compton.svg` as icon, and discussed about its utility [picom#988](https://github.com/yshui/picom/issues/988)

##### Expected Behavior
Display an icon in menu

##### Current Behavior
Default or no icon is displayed in menu entry

##### Possible Solution
Integrate the icon compton.svg in this repo, rename it.

**Comment by redtide** [comment]
this was somewhat a suspended thing that I lost track of. I was hoping that someone with graphic design ability contributed either upstream or here, but there wasn't.
Else, I could use a generic `preferences-system` as I did for sddm-conf. Using the compton icon makes no sense to me as IIUC it uses the initial letter of the old application, which doesn't fit here.

**Comment by redtide** [comment]
fixed in f80ef55

**Comment by papoteur-mga** [comment]
Thanks,
I applied the change in our Mageia's package.
